os: windows
language: bash

install:
  - choco install python --version 3.7.2 -y # TODO - test both py3.7 and py3.6
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  - python -m pip install -U pip wheel
  - pip install poetry
  - poetry install

script:
  - poetry run invoke test --cov=.
