os: windows
language: bash

install:
  - choco install python -y # 3.7.2 right now; TODO - test both py3.7 and py3.6
  - pip install poetry
  - poetry install

script:
  - poetry run invoke test --cov=.
